const express = require('express');
const db = require('../db');
const { getStripe } = require('../lib/stripe');
const { bookingLimiter } = require('../middleware/rateLimit');

const router = express.Router();

// Token-gated: the deposit_token is a high-entropy random value generated by
// the admin dashboard and shared with the customer directly (e.g. by email),
// so knowing it is equivalent to being the intended recipient - the same
// pattern used for password reset links.
router.get('/:token', bookingLimiter, async (req, res) => {
  const booking = db.prepare(
    `SELECT b.*, c.name AS car_name FROM bookings b JOIN cars c ON c.id = b.car_id WHERE b.deposit_token = ?`
  ).get(req.params.token);

  if (!booking) return res.status(404).json({ error: 'This deposit link is invalid.' });

  if (booking.deposit_status !== 'requested') {
    return res.json({ status: booking.deposit_status, car_name: booking.car_name, amount_cents: booking.deposit_amount_cents });
  }

  const stripe = getStripe();
  if (!stripe) return res.status(503).json({ error: 'Online payment is not configured.' });

  try {
    const intent = await stripe.paymentIntents.retrieve(booking.deposit_payment_intent_id);
    res.json({
      status: 'requested',
      car_name: booking.car_name,
      amount_cents: booking.deposit_amount_cents,
      currency: booking.currency,
      capture_method: booking.deposit_capture_method,
      client_secret: intent.client_secret
    });
  } catch (err) {
    console.error('Could not retrieve deposit PaymentIntent:', err);
    res.status(502).json({ error: 'Could not load this deposit request. Please contact us.' });
  }
});

module.exports = router;
